### ISSUE TITLE
Ark Survival Evolved Template

### ISSUE THREAD

**Issue by ghost** [PufferPanel/templates#186]
Hello 

I am having a problem with the ark server template for pufferpanel because when I boot up the server and try join through epic games it wont let me join I keep getting this error 
![image](https://user-images.githubusercontent.com/110034225/201679360-6dbb6a06-2952-4757-8d40-2f663434e9ea.png)
and this is what is says on my console 
![image](https://user-images.githubusercontent.com/110034225/201679453-26d3b1bb-0114-47db-ae49-898bc0d5598b.png)
is there any way i can fix this

**Comment by CristianEduardMihai** [comment]
Hi ! I never hosted ARK before, but I did some googling and found that the `IsSteamRunning()` error is common on servers, as the Steam client is not running. The timeout could be caused by misconfigured iptables. Check out this [old] thread: https://steamcommunity.com/app/346110/discussions/0/594820656477200972

**Comment by ghost** [comment]
Hello Thanks I will check it out but i did recently switch to pterodactyl panel and i get the same error but thanks

**Comment by LexFuturorum** [comment]
looks more like a firewall or port forwarding issue to me as ark and 7dtd are notorious for beeing a dick with console output
