### ISSUE TITLE
The XMS Flag is not mentioned in the minecraft-paper template!

### ISSUE THREAD

**Issue by slash1div** [PufferPanel/templates#187]
### I found this in Paper, but I also saw this in Spigot. If possible, please check all other MC based servers you have for this! It's recommended for most Paper servers.

The flags xms and xmx are supposed to be the same. However, xms is not referenced, so it is defaulted to 2gb. Fixing this leads to a slight performance increase.
https://github.com/PufferPanel/templates/blob/3ac427dd8ea995019fbaea7efe812ddca644c881/minecraft-paper/minecraft-paper.json#L28

--

To fix this issue, add the Xms flag before Xmx.
Replace Line 28 with this:
```json
    "command": "${java} -Xms${memory}M -Xmx${memory}M -Dterminal.jline=false -Dterminal.ansi=true -Djline.terminal=jline.UnsupportedTerminal -Dlog4j2.formatMsgNoLookups=true -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar paper.jar nogui",
```

---

Before: 
![image](https://user-images.githubusercontent.com/83387831/202889294-8187fd4e-b186-4c2c-b489-83d8cc68fd86.png)

After:
![image](https://user-images.githubusercontent.com/83387831/202889305-2a0029ac-2880-4a19-9ac7-435159a9a825.png)

**Comment by LordRalex** [comment]
They are not "always supposed to be the same". Anything that claims always set them to true is blindly doing it, and doesn't explain the why. It's a "recommendation", not a "requirement" even by Oracle.

It is always dependent on the GC being used, and depends on the behavior that is desired. While the only requirement is that it sets the "initial" heap size, there is 0 guarantee it remains that way.

With G1GC, XMS defines the "minimum" size of the heap, and will not release memory back to the OS below this value. Roughly, and simplicity, it follows like this:
- With an XMS of 10GB, if the JVM only actually needs 1GB, you're still locking 9GB of the memory away from the OS, and it will never set it
- With XMS not set, and the JVM currently is using 1GB but has currently 10GB of heap allocated, it will return 9GB back to the OS. 

This changes it's meaning if another GC is used.

ZGC also follows this same behavior.

Parallel doesn't release memory back to the OS, but it also treats it as the initial.

But, even then, this is entirely a "what do you want" problem.

Running 1 server? It won't matter.
Running several servers? It will. Releasing memory so that another server could "burst" up higher is a bit nicer. 

This counter-argument is also that GC runs over "less" memory, so if it's not using the full heap yet, you're running less work to analyze said heap. 

Such tuning should be done on a case-by-case basis. If your heap is 10GB, then it's not ideal to define it all up-front. If it's 1GB, it isn't as much of an issue.

While it's probably not going to release, the impact is basically 0 for it to be smaller, and grow when it needs to.

--------

Even with talking with server owners do this for a living, setting Xms barely does anything except in *very* specific circumstances. 

We're not going to add it. There isn't a point.
